version: '3.6'

services:

  nikitadb:
    image: nikitadb

    build:
      context: .
      target: nikitadb_build

    # Share ports with the host.
    network_mode: "host"

    # Pass stdin through to the executable.
    stdin_open: true
    tty: true

    # Make tini be PID 1 to force Ctrl-C to kill underlying proccess.
    init: true

  api-server:
    image: api-server

    build:
      context: .
      target: api_server_build

    # depends_on:
    #   - nikitadb

    # Share ports with the host.
    network_mode: "host"

    # Pass stdin through to the executable.
    stdin_open: true
    tty: true

    # Make tini be PID 1 to force Ctrl-C to kill underlying proccess.
    init: true

  # test-client:
  #   image: test-client

  #   build:
  #     context: .
  #     target: hello_world_client

  #   depends_on:
  #     - nikitadb

  #   # Share ports with the host.
  #   network_mode: "host"

  #   # Pass stdin through to the executable.
  #   stdin_open: true
  #   tty: true

  #   # Make tini be PID 1 to force Ctrl-C to kill underlying proccess.
  #   init: true
