version: '3.6'

services:

  nikitadb:
    image: nikitadb

    build:
      context: .
      target: nikitadb_build

    # Make tini be PID 1 to force Ctrl-C to kill underlying proccess.
    init: true

  api-server:
    image: api-server

    build:
      context: .
      target: api_server_build

    depends_on:
      - nikitadb

    ports:
      - "8080:8080"

    # Make tini be PID 1 to force Ctrl-C to kill underlying proccess.
    init: true
